# Generated by Django 2.1 on 2018-11-26 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Area do conhecimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='esta ativa?')),
            ],
            options={
                'verbose_name': 'Area do Conhecimento',
                'verbose_name_plural': 'Áreas do conhecimento',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='texto da pergunta')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AreaConhecimento')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(blank=True, default=0, verbose_name='pontos')),
                ('perguntas_realizadas', models.ManyToManyField(blank=True, related_name='per_ral', to='core.Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='texto da resposta')),
                ('verdade', models.BooleanField(verbose_name='a verdadeira?')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='SalaResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='codigo da sala de resposta')),
                ('ativo', models.BooleanField(default=True, verbose_name='sala ativa?')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AreaConhecimento')),
                ('perguntas', models.ManyToManyField(blank=True, to='core.Pergunta')),
            ],
            options={
                'verbose_name': 'Sala de Resposta',
                'verbose_name_plural': 'Salas de Respostas',
            },
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='respostas_computadas',
            field=models.ManyToManyField(blank=True, related_name='res_com', to='core.Resposta'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SalaResposta'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='respostas',
            field=models.ManyToManyField(blank=True, to='core.Resposta'),
        ),
    ]
